name: azure_notify_hub
description: Flutter plugin for Azure Notification Hubs
version: 1.0.0
homepage: https://github.com/GhostBman/azure_notify_hub.git

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.multicode.azure_notify_hub
    pluginClass: AzureNotificationhubsFlutterPlugin